/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.de.tcp.text.to.sound;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.*;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MetaEventListener;
import javax.sound.midi.MetaMessage;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;
import javax.sound.midi.Sequence;
import javax.sound.midi.Sequencer;
import javax.sound.midi.Synthesizer;
import javax.sound.midi.Track;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;
import javax.swing.text.BadLocationException;
/**
 *
 * @author Ottoni Bastos
 */
public class ProjetoTCP_UI extends javax.swing.JFrame {

TXT txt;
String path;
String dummy;
MIDI midi= new MIDI();
Instrument instrument = new Piano();
Player player = new Player(64,60,0);
Note[] notes;
Sequence sequence;
Track track;
Sequencer sequencer;
Synthesizer synthesizer;
int playcount=0;
static String message = new String("<html><b>Como usar:<br/><br/>- Carácteres de A a G:"
        + " representam notas Lá-Sí-Dó-Ré-Mí-Fá,respectivamente.<br/><br/>"
        + "- Carácteres I,O,U: Repetem a última nota tocada.<br/><br/>"
        + "- /1,/2,/4,/8,/16 e /32: modificam o tamanho das notas a serem tocadas a partir daquele momento.</b><br/><br/>"
        + "<b>**Exemplos: </b><br/><br/>"
        + "*<i>\"/1AxBxCxD\" - tocará a nota Lá,Sí,Dó,Ré inteiras.</i><br/><br/> "
        + "*<i>\"/4BxCxDxE\" - Tocará um quarto das notas Sí,Dó,Ré,Mí.</i><br/><br/> "
        + "<b>- ! e ?: Aumenta e diminui o volume,respectivamente<br/><br/>"
        + "- # e J: Aumente e diminui a nota em um semitom,respectivamente.<br/><br/>"
        + "- S: Representa o pedal de sustentação do piano.</b></html>");
    /**
     * Creates new form ProjetoTCP_UI
     */
    public ProjetoTCP_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        Ajuda = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Sobre = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane(jTextArea2,
            JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jTextArea2 = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jFileChooser2.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        Ajuda.setTitle("Ajuda");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Como usar:\n\n- Carácteres de A a G: representam notas Lá-Sí-Dó-Ré-Mí-Fá,respectivamente.\n\n- Carácteres I,O,U: Repetem a última nota tocada.\n\n- /1,/2,/4,/8,/16 e /32: modificam o tamanho das notas a serem tocadas a partir daquele momento.\n\n  Exemplos: \"/1A\" - tocará a nota Lá inteira.\n                    \"/4B\" - Tocará um quarto de nota Sí.\n\n- ! e ?: Aumenta e diminui o volume,respectivamente\n\n- # e J: Aumente e diminui a nota em um semitom,respectivamente.\n\n- S: Representa o pedal de sustentação do piano.");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AjudaLayout = new javax.swing.GroupLayout(Ajuda.getContentPane());
        Ajuda.getContentPane().setLayout(AjudaLayout);
        AjudaLayout.setHorizontalGroup(
            AjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(AjudaLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jButton1)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        AjudaLayout.setVerticalGroup(
            AjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Ajuda.getAccessibleContext().setAccessibleDescription("Hello");

        Sobre.setTitle("Sobre");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Este programa foi criado com o intuito de simular o som de um piano \nutilizando letras do alfabeto, formando melodias. \n\nQualquer dúvida sobre o funcionamento, acesse Menu 'Arquivo' e 'Ajuda'.\n\nCriado por:\nMatheus Bica\nAlberto Pena\nOttoni Bastos");
        jScrollPane3.setViewportView(jTextArea3);

        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharSobre(evt);
            }
        });

        javax.swing.GroupLayout SobreLayout = new javax.swing.GroupLayout(Sobre.getContentPane());
        Sobre.getContentPane().setLayout(SobreLayout);
        SobreLayout.setHorizontalGroup(
            SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(SobreLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton3)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        SobreLayout.setVerticalGroup(
            SobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jButton3.getAccessibleContext().setAccessibleName("Fechar_Sobre");

        Sobre.getAccessibleContext().setAccessibleName("Sobre");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho de TCP - 2015/1");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Área de Texto"));
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Digite aqui o texto a ser carregado");
        jScrollPane2.setViewportView(jTextArea2);

        jToggleButton1.setText("Play");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jToggleButton1)
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Carregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salvar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Ajuda");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Sobre");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Área do texto");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
      
    }//GEN-LAST:event_jMenu1ActionPerformed
    //Botão carregar
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         jFileChooser1.showOpenDialog(this);
        String path = new String(jFileChooser1.getSelectedFile().toString());
    try {
        jTextArea2.setText("");
        Scanner scanner = new Scanner(new FileInputStream(path),"UTF-8");
        while(scanner.hasNextLine()){
        jTextArea2.append(scanner.nextLine()+ "\n");
        }
    } catch (FileNotFoundException ex) {
        Logger.getLogger(ProjetoTCP_UI.class.getName()).log(Level.SEVERE, null, ex);
    }
     
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //Botão de Play/Pause
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    
    //Se Botão foi pressionado,o label muda para "Pause" e a música toca.
    if(jToggleButton1.isSelected() && playcount == 0){
        jToggleButton1.setText("Pause");
        jButton2.setEnabled(true);
        
        try {
            playcount++;
            dummy = new String(jTextArea2.getText());
            notes = new Note[dummy.length()];
            for(int i=0;i<dummy.length();i++){
                //System.out.println(dummy.charAt(i));
                notes[i]= new Note(dummy.charAt(i));
                                             }
        
            sequence = new Sequence(Sequence.PPQ, 16);
            track = sequence.createTrack( );  // Begin with a new track
            player.addTrack(track,midi,instrument,notes);
            sequencer = MidiSystem.getSequencer( );
            sequencer.open( );  
            //synthesizer = MidiSystem.getSynthesizer( );
            //synthesizer.open( );
            //sequencer.getTransmitter( ).setReceiver(synthesizer.getReceiver( ));

            // Specify the sequence to play, and the tempo to play it at
            sequencer.setSequence(sequence);
            sequencer.setTempoInBPM(instrument.tempo);

            //sequencer.start();
           
            // Pra saber quando a música acaba.
            sequencer.addMetaEventListener(new MetaEventListener( ) {
                public void meta(MetaMessage m) {
                    // quando a música acabar,o botão de play é resetado!
                    if (m.getType( ) == midi.getEndOfTrack()){
                        
                        jToggleButton1.setText("Play");
                        jToggleButton1.setSelected(false);
                        playcount = 0; 
                        sequencer.stop();
                        jButton2.setEnabled(false);
                        
                    };
                                                }
                                                                    }
                                          );
            // And start playing now.
            
            sequencer.start( );
            
            
        //txt= new TXT(jTextArea2);
        }catch(InvalidMidiDataException ex){
         Logger.getLogger(ProjetoTCP_UI.class.getName()).log(Level.SEVERE, null, ex);
        }catch(MidiUnavailableException ex){
         Logger.getLogger(ProjetoTCP_UI.class.getName()).log(Level.SEVERE, null, ex);
    }
               
               
    }
    //Se o botão play for pressionado no meio da musica,
    //a musica toca a partir de onde parou!
    else if(jToggleButton1.isSelected()){
        sequencer.start(); jToggleButton1.setText("Pause");}
 
    //se o botão pause for pressionado,a musica para.
    else {sequencer.stop(); jToggleButton1.setText("Play");}
    
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    //Botão sair
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //Botão Salvar 
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        jFileChooser2.showSaveDialog(this);
        String fName = jFileChooser2.getSelectedFile().getName();
        String fPath = jFileChooser2.getSelectedFile().getPath();
        FileWriter fw;  
        PrintWriter pw;  
        
        int i=0;
        int j=0;
        int k;
        try{ 
            
            fw = new FileWriter(fPath + ".txt");  
            
            pw = new PrintWriter(fw);          
        
            while(i<jTextArea2.getLineCount()){
            j= jTextArea2.getLineStartOffset(i);
            
            k= jTextArea2.getLineEndOffset(i)-jTextArea2.getLineStartOffset(i);
            if(i==jTextArea2.getLineCount()-1){pw.println(jTextArea2.getText(j, k));}
            else {pw.println(jTextArea2.getText(j, k-1));}
            i++;
            }
            pw.close();  
        }catch(IOException e){  
           System.out.println(e.getMessage());   
        }catch(NullPointerException e){  
        } catch (BadLocationException ex) {  
        Logger.getLogger(ProjetoTCP_UI.class.getName()).log(Level.SEVERE, null, ex);
    }  
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed
//Se apertar o botão "Ajuda",abre a janela com uma colinha
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JFrame frame = new JFrame( "Ajuda" );
        JLabel label = new JLabel(message,JLabel.LEFT);
        label.setVerticalAlignment(JLabel.TOP);
        frame.getContentPane().add( label );
        frame.setLocation(400, 0);
        frame.setSize( 700, 400 );
        frame.setVisible( true );
    }//GEN-LAST:event_jMenuItem5ActionPerformed
//Fecha a janela de ajuda.
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ajuda.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        sequence.deleteTrack(track);
        sequencer.stop();
        sequencer.close();
        jToggleButton1.setText("Play");
        jToggleButton1.setSelected(false);
        playcount = 0; 
        jButton2.setEnabled(false);
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonFecharSobre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharSobre
        Sobre.setVisible(false);
    }//GEN-LAST:event_jButtonFecharSobre

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JFrame frame = new JFrame( "Sobre" );
        JLabel label = new JLabel(message,JLabel.LEFT);
        label.setVerticalAlignment(JLabel.TOP);
        frame.getContentPane().add( label );
        frame.setLocation(400, 0);
        frame.setSize( 700, 400 );
        frame.setVisible( true );
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException{
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoTCP_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoTCP_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoTCP_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoTCP_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            //JTextArea area = new JTextArea();
            
            
            
            
            public void run() {
                new ProjetoTCP_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Ajuda;
    private javax.swing.JDialog Sobre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
